import { DatabaseSchema, Exam, Question, Admin, Student, ExamAttempt, StudentAnswer } from "@/types";
import bcrypt from "bcryptjs";

export function generateInitialData(): DatabaseSchema {
  const suhasPasswordHash = bcrypt.hashSync("Suhas#Admin2026!$9x", 10);
  const now = new Date().toISOString();

  const admins: Admin[] = [
    {
      id: "admin-suhas",
      name: "Suhas",
      email: "suhas@exam.com",
      passwordHash: suhasPasswordHash,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const exams: Exam[] = [
    {
      id: "exam-math-101",
      title: "Mathematics & Logical Reasoning Unit Test",
      description: "Standardized assessment covering algebra, arithmetic, logical patterns, and geometry.",
      subject: "Mathematics",
      durationMinutes: 20,
      totalQuestions: 10,
      marksPerQuestion: 2,
      negativeMarks: 0,
      shuffleQuestions: true,
      shuffleOptions: true,
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "exam-cs-201",
      title: "Computer Science & Web Technologies Exam",
      description: "Comprehensive test on Web Protocols, JavaScript, Data Structures, and Database fundamentals.",
      subject: "Computer Science",
      durationMinutes: 30,
      totalQuestions: 10,
      marksPerQuestion: 3,
      negativeMarks: 0.5,
      shuffleQuestions: true,
      shuffleOptions: true,
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "exam-sci-301",
      title: "General Science & Physics Aptitude Test",
      description: "Core physical science, mechanics, optics, and chemistry principles.",
      subject: "General Science",
      durationMinutes: 15,
      totalQuestions: 6,
      marksPerQuestion: 1,
      negativeMarks: 0,
      shuffleQuestions: true,
      shuffleOptions: false,
      status: "active",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const questions: Question[] = [
    // Math Exam Questions
    {
      id: "q-math-1",
      examId: "exam-math-101",
      questionText: "What is the value of 15% of 480?",
      optionA: "64",
      optionB: "72",
      optionC: "80",
      optionD: "68",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-2",
      examId: "exam-math-101",
      questionText: "If 3x + 7 = 28, what is the value of x?",
      optionA: "5",
      optionB: "7",
      optionC: "6",
      optionD: "8",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-3",
      examId: "exam-math-101",
      questionText: "What is the perimeter of a rectangle with length 14 cm and width 9 cm?",
      optionA: "46 cm",
      optionB: "52 cm",
      optionC: "126 cm",
      optionD: "48 cm",
      correctAnswer: "A",
      createdAt: now,
    },
    {
      id: "q-math-4",
      examId: "exam-math-101",
      questionText: "Find the next number in sequence: 2, 6, 12, 20, 30, ?",
      optionA: "40",
      optionB: "42",
      optionC: "44",
      optionD: "46",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-5",
      examId: "exam-math-101",
      questionText: "What is the sum of interior angles of a pentagon?",
      optionA: "360 degrees",
      optionB: "540 degrees",
      optionC: "720 degrees",
      optionD: "450 degrees",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-6",
      examId: "exam-math-101",
      questionText: "If a car travels 240 km in 3 hours, what is its average speed?",
      optionA: "70 km/h",
      optionB: "75 km/h",
      optionC: "80 km/h",
      optionD: "85 km/h",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-math-7",
      examId: "exam-math-101",
      questionText: "What is the square root of 1764?",
      optionA: "42",
      optionB: "44",
      optionC: "38",
      optionD: "46",
      correctAnswer: "A",
      createdAt: now,
    },
    {
      id: "q-math-8",
      examId: "exam-math-101",
      questionText: "A train 150m long passes a pole in 9 seconds. What is the train's speed in km/h?",
      optionA: "50 km/h",
      optionB: "60 km/h",
      optionC: "65 km/h",
      optionD: "72 km/h",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-9",
      examId: "exam-math-101",
      questionText: "Solve: (25 × 4) + (18 ÷ 2) - 9",
      optionA: "90",
      optionB: "100",
      optionC: "109",
      optionD: "99",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-math-10",
      examId: "exam-math-101",
      questionText: "The ratio of boys to girls in a class of 45 students is 3:2. How many boys are there?",
      optionA: "27",
      optionB: "18",
      optionC: "25",
      optionD: "30",
      correctAnswer: "A",
      createdAt: now,
    },

    // Computer Science Exam Questions
    {
      id: "q-cs-1",
      examId: "exam-cs-201",
      questionText: "Which HTTP status code signifies 'Created' after a successful POST request?",
      optionA: "200",
      optionB: "201",
      optionC: "204",
      optionD: "301",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-cs-2",
      examId: "exam-cs-201",
      questionText: "What data structure operates on a Last-In, First-Out (LIFO) principle?",
      optionA: "Queue",
      optionB: "Stack",
      optionC: "Heap",
      optionD: "Binary Tree",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-cs-3",
      examId: "exam-cs-201",
      questionText: "In relational databases, which SQL clause is used to filter aggregated group results?",
      optionA: "WHERE",
      optionB: "ORDER BY",
      optionC: "HAVING",
      optionD: "LIMIT",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-cs-4",
      examId: "exam-cs-201",
      questionText: "Which JavaScript keyword declares a block-scoped variable that cannot be reassigned?",
      optionA: "var",
      optionB: "let",
      optionC: "const",
      optionD: "static",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-cs-5",
      examId: "exam-cs-201",
      questionText: "What is the average time complexity of searching an element in a balanced Binary Search Tree (BST)?",
      optionA: "O(1)",
      optionB: "O(log n)",
      optionC: "O(n)",
      optionD: "O(n log n)",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-cs-6",
      examId: "exam-cs-201",
      questionText: "What does DNS stand for in computer networking?",
      optionA: "Domain Name System",
      optionB: "Data Network Service",
      optionC: "Dynamic Node Server",
      optionD: "Distributed Network System",
      correctAnswer: "A",
      createdAt: now,
    },
    {
      id: "q-cs-7",
      examId: "exam-cs-201",
      questionText: "Which HTTP header is commonly used to send JWT authorization tokens?",
      optionA: "Content-Type",
      optionB: "Authorization",
      optionC: "Accept-Token",
      optionD: "User-Agent",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-cs-8",
      examId: "exam-cs-201",
      questionText: "Which normal form removes transitive dependencies in relational database normalization?",
      optionA: "1NF",
      optionB: "2NF",
      optionC: "3NF",
      optionD: "BCNF",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-cs-9",
      examId: "exam-cs-201",
      questionText: "Which of the following is NOT a valid JavaScript data type?",
      optionA: "Symbol",
      optionB: "BigInt",
      optionC: "Undefined",
      optionD: "Float64",
      correctAnswer: "D",
      createdAt: now,
    },
    {
      id: "q-cs-10",
      examId: "exam-cs-201",
      questionText: "Which CSS property is used to create a flexbox container?",
      optionA: "display: flex",
      optionB: "flex-direction: row",
      optionC: "box-sizing: border-box",
      optionD: "align-items: center",
      correctAnswer: "A",
      createdAt: now,
    },

    // Science Exam Questions
    {
      id: "q-sci-1",
      examId: "exam-sci-301",
      questionText: "What is the acceleration due to gravity on Earth's surface (approximate)?",
      optionA: "8.9 m/s²",
      optionB: "9.8 m/s²",
      optionC: "10.8 m/s²",
      optionD: "11.2 m/s²",
      correctAnswer: "B",
      createdAt: now,
    },
    {
      id: "q-sci-2",
      examId: "exam-sci-301",
      questionText: "Which gas is most abundant in Earth's atmosphere?",
      optionA: "Oxygen",
      optionB: "Carbon Dioxide",
      optionC: "Nitrogen",
      optionD: "Argon",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-sci-3",
      examId: "exam-sci-301",
      questionText: "What is the chemical formula for table salt?",
      optionA: "NaCl",
      optionB: "KCl",
      optionC: "CaCl2",
      optionD: "Na2CO3",
      correctAnswer: "A",
      createdAt: now,
    },
    {
      id: "q-sci-4",
      examId: "exam-sci-301",
      questionText: "Which particle carries a negative electric charge in an atom?",
      optionA: "Proton",
      optionB: "Neutron",
      optionC: "Electron",
      optionD: "Positron",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-sci-5",
      examId: "exam-sci-301",
      questionText: "What unit is used to measure electrical resistance?",
      optionA: "Volt",
      optionB: "Ampere",
      optionC: "Ohm",
      optionD: "Watt",
      correctAnswer: "C",
      createdAt: now,
    },
    {
      id: "q-sci-6",
      examId: "exam-sci-301",
      questionText: "Which organelle is known as the powerhouse of the cell?",
      optionA: "Nucleus",
      optionB: "Ribosome",
      optionC: "Mitochondria",
      optionD: "Golgi apparatus",
      correctAnswer: "C",
      createdAt: now,
    },
  ];

  const students: Student[] = [
    {
      id: "stu-1",
      name: "Rahul Patil",
      rollNumber: "23",
      division: "A",
      email: "rahul.patil@school.edu",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "stu-2",
      name: "Priya Sharma",
      rollNumber: "15",
      division: "A",
      email: "priya.sharma@school.edu",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "stu-3",
      name: "Amit Deshmukh",
      rollNumber: "42",
      division: "B",
      email: "amit.deshmukh@school.edu",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "stu-4",
      name: "Sneha Kulkarni",
      rollNumber: "08",
      division: "A",
      email: "sneha.k@school.edu",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const mathQuestions = questions.filter((q) => q.examId === "exam-math-101");
  const mathQIds = mathQuestions.map((q) => q.id);

  const examAttempts: ExamAttempt[] = [
    {
      id: "attempt-1",
      examId: "exam-math-101",
      studentId: "stu-1",
      startedAt: new Date(Date.now() - 3600000).toISOString(),
      submittedAt: new Date(Date.now() - 2500000).toISOString(),
      expiresAt: new Date(Date.now() - 2400000).toISOString(),
      status: "submitted",
      totalQuestions: 10,
      correctAnswers: 9,
      incorrectAnswers: 1,
      unansweredQuestions: 0,
      marksObtained: 18,
      totalPossibleMarks: 20,
      percentage: 90,
      questionOrder: [...mathQIds].reverse(),
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 2500000).toISOString(),
    },
    {
      id: "attempt-2",
      examId: "exam-math-101",
      studentId: "stu-2",
      startedAt: new Date(Date.now() - 7200000).toISOString(),
      submittedAt: new Date(Date.now() - 6100000).toISOString(),
      expiresAt: new Date(Date.now() - 6000000).toISOString(),
      status: "submitted",
      totalQuestions: 10,
      correctAnswers: 7,
      incorrectAnswers: 2,
      unansweredQuestions: 1,
      marksObtained: 14,
      totalPossibleMarks: 20,
      percentage: 70,
      questionOrder: ["q-math-3", "q-math-1", "q-math-7", "q-math-2", "q-math-8", "q-math-4", "q-math-9", "q-math-5", "q-math-10", "q-math-6"],
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 6100000).toISOString(),
    },
    {
      id: "attempt-3",
      examId: "exam-math-101",
      studentId: "stu-3",
      startedAt: new Date(Date.now() - 10800000).toISOString(),
      submittedAt: new Date(Date.now() - 9600000).toISOString(),
      expiresAt: new Date(Date.now() - 9500000).toISOString(),
      status: "submitted",
      totalQuestions: 10,
      correctAnswers: 5,
      incorrectAnswers: 4,
      unansweredQuestions: 1,
      marksObtained: 10,
      totalPossibleMarks: 20,
      percentage: 50,
      questionOrder: ["q-math-5", "q-math-9", "q-math-2", "q-math-4", "q-math-1", "q-math-6", "q-math-10", "q-math-3", "q-math-7", "q-math-8"],
      createdAt: new Date(Date.now() - 10800000).toISOString(),
      updatedAt: new Date(Date.now() - 9600000).toISOString(),
    },
  ];

  const studentAnswers: StudentAnswer[] = [
    // Rahul Patil's answers (Attempt 1: 9/10 correct)
    { id: "sa-1-1", attemptId: "attempt-1", questionId: "q-math-10", displayedPosition: 1, selectedAnswer: "A", normalizedAnswer: "A", correctAnswer: "A", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-2", attemptId: "attempt-1", questionId: "q-math-9", displayedPosition: 2, selectedAnswer: "B", normalizedAnswer: "B", correctAnswer: "B", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-3", attemptId: "attempt-1", questionId: "q-math-8", displayedPosition: 3, selectedAnswer: "B", normalizedAnswer: "B", correctAnswer: "B", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-4", attemptId: "attempt-1", questionId: "q-math-7", displayedPosition: 4, selectedAnswer: "A", normalizedAnswer: "A", correctAnswer: "A", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-5", attemptId: "attempt-1", questionId: "q-math-6", displayedPosition: 5, selectedAnswer: "C", normalizedAnswer: "C", correctAnswer: "C", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-6", attemptId: "attempt-1", questionId: "q-math-5", displayedPosition: 6, selectedAnswer: "B", normalizedAnswer: "B", correctAnswer: "B", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-7", attemptId: "attempt-1", questionId: "q-math-4", displayedPosition: 7, selectedAnswer: "B", normalizedAnswer: "B", correctAnswer: "B", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-8", attemptId: "attempt-1", questionId: "q-math-3", displayedPosition: 8, selectedAnswer: "A", normalizedAnswer: "A", correctAnswer: "A", isCorrect: true, marksAwarded: 2 },
    { id: "sa-1-9", attemptId: "attempt-1", questionId: "q-math-2", displayedPosition: 9, selectedAnswer: "A", normalizedAnswer: "A", correctAnswer: "B", isCorrect: false, marksAwarded: 0 }, // Mistake
    { id: "sa-1-10", attemptId: "attempt-1", questionId: "q-math-1", displayedPosition: 10, selectedAnswer: "B", normalizedAnswer: "B", correctAnswer: "B", isCorrect: true, marksAwarded: 2 },
  ];

  return {
    admins,
    students,
    exams,
    questions,
    examAttempts,
    studentAnswers,
  };
}
